
package com.docking.wsdl.xlt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderOnlineServiceService", targetNamespace = "http://service.hop.service.ws.hlt.com/", wsdlLocation = "http://47.92.33.48:8086/xms/services/order?wsdl")
public class OrderOnlineServiceService
    extends Service
{

    private final static URL ORDERONLINESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERONLINESERVICESERVICE_EXCEPTION;
    private final static QName ORDERONLINESERVICESERVICE_QNAME = new QName("http://service.hop.service.ws.hlt.com/", "OrderOnlineServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://47.92.33.48:8086/xms/services/order?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERONLINESERVICESERVICE_WSDL_LOCATION = url;
        ORDERONLINESERVICESERVICE_EXCEPTION = e;
    }

    public OrderOnlineServiceService() {
        super(__getWsdlLocation(), ORDERONLINESERVICESERVICE_QNAME);
    }

    public OrderOnlineServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERONLINESERVICESERVICE_QNAME, features);
    }

    public OrderOnlineServiceService(URL wsdlLocation) {
        super(wsdlLocation, ORDERONLINESERVICESERVICE_QNAME);
    }

    public OrderOnlineServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERONLINESERVICESERVICE_QNAME, features);
    }

    public OrderOnlineServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderOnlineServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderOnlineService
     */
    @WebEndpoint(name = "OrderOnlineServicePort")
    public OrderOnlineService getOrderOnlineServicePort() {
        return super.getPort(new QName("http://service.hop.service.ws.hlt.com/", "OrderOnlineServicePort"), OrderOnlineService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderOnlineService
     */
    @WebEndpoint(name = "OrderOnlineServicePort")
    public OrderOnlineService getOrderOnlineServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.hop.service.ws.hlt.com/", "OrderOnlineServicePort"), OrderOnlineService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERONLINESERVICESERVICE_EXCEPTION!= null) {
            throw ORDERONLINESERVICESERVICE_EXCEPTION;
        }
        return ORDERONLINESERVICESERVICE_WSDL_LOCATION;
    }

}
