
package com.docking.wsdl.xlt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderOnlineService", targetNamespace = "http://service.hop.service.ws.hlt.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderOnlineService {


    /**
     * 
     * @param userToken
     * @param createOrderRequestV2
     * @return
     *     returns com.docking.wsdl.xlt.CreateOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public CreateOrderResponse createAndAuditOrderV3(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "createOrderRequestV2", partName = "createOrderRequestV2")
        CreateOrderRequest createOrderRequestV2);

    /**
     * 
     * @param userToken
     * @param createOrderRequestV2
     * @return
     *     returns com.docking.wsdl.xlt.CreateOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public CreateOrderResponse createOrderV2(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "createOrderRequestV2", partName = "createOrderRequestV2")
        CreateOrderRequestV2 createOrderRequestV2);

    /**
     * 
     * @param beginDate
     * @param apiToken
     * @param endDate
     * @param page
     * @return
     *     returns com.docking.wsdl.xlt.OrderInfoResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public OrderInfoResponse orderInfoList(
        @WebParam(name = "apiToken", partName = "apiToken")
        String apiToken,
        @WebParam(name = "beginDate", partName = "beginDate")
        XMLGregorianCalendar beginDate,
        @WebParam(name = "endDate", partName = "endDate")
        XMLGregorianCalendar endDate,
        @WebParam(name = "page", partName = "page")
        int page);

    /**
     * 
     * @param userToken
     * @param lookupOrderRequest
     * @return
     *     returns com.docking.wsdl.xlt.LookupOrderVirtualWnoResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LookupOrderVirtualWnoResponse lookupOrderVirtualWno(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "lookupOrderRequest", partName = "lookupOrderRequest")
        LookupOrderRequest lookupOrderRequest);

    /**
     * 
     * @param userToken
     * @param printOrderRequest
     * @return
     *     returns com.docking.wsdl.xlt.PrintOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public PrintOrderResponse printOrder(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "printOrderRequest", partName = "printOrderRequest")
        PrintOrderRequest printOrderRequest);

    /**
     * 
     * @param userToken
     * @param pickUpRequest
     * @return
     *     returns com.docking.wsdl.xlt.PickUpResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public PickUpResponse wishPickUp(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "pickUpRequest", partName = "pickUpRequest")
        PickUpRequest pickUpRequest);

    /**
     * 
     * @param userToken
     * @param createOrderRequestV2
     * @return
     *     returns com.docking.wsdl.xlt.CreateOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public CreateOrderResponse createAndAuditOrderV2(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "createOrderRequestV2", partName = "createOrderRequestV2")
        CreateOrderRequestV2 createOrderRequestV2);

    /**
     * 
     * @param userToken
     * @param calculateChargeRequest
     * @return
     *     returns com.docking.wsdl.xlt.CalculateChargeResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public CalculateChargeResponse calculateCharge(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "calculateChargeRequest", partName = "calculateChargeRequest")
        CalculateChargeRequest calculateChargeRequest);

    /**
     * 
     * @param userToken
     * @param orderNo
     * @return
     *     returns com.docking.wsdl.xlt.DeleteOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public DeleteOrderResponse deleteOrder3(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "orderNo", partName = "orderNo")
        String orderNo);

    /**
     * 
     * @param userToken
     * @param orderId
     * @return
     *     returns com.docking.wsdl.xlt.DeleteOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public DeleteOrderResponse deleteOrder(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId);

    /**
     * 
     * @param userToken
     * @param orderId
     * @return
     *     returns com.docking.wsdl.xlt.AuditOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public AuditOrderResponse auditOrder(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "orderId", partName = "orderId")
        long orderId);

    /**
     * 
     * @param userToken
     * @param orderNo
     * @return
     *     returns com.docking.wsdl.xlt.DeleteOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public DeleteOrderResponse deleteOrder2(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "orderNo", partName = "orderNo")
        String orderNo);

    /**
     * 
     * @param userToken
     * @param trackingNo
     * @return
     *     returns com.docking.wsdl.xlt.GetTrackResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public GetTrackResponse getTrack(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "trackingNo", partName = "trackingNo")
        String trackingNo);

    /**
     * 
     * @param userToken
     * @param createOrderRequest
     * @return
     *     returns com.docking.wsdl.xlt.CreateOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public CreateOrderResponse createOrder(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "createOrderRequest", partName = "createOrderRequest")
        CreateOrderRequest createOrderRequest);

    /**
     * 
     * @param userToken
     * @param lookupOrderRequest
     * @return
     *     returns com.docking.wsdl.xlt.LookupOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LookupOrderResponse lookupOrder(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "lookupOrderRequest", partName = "lookupOrderRequest")
        LookupOrderRequest lookupOrderRequest);

    /**
     * 
     * @param userToken
     * @param lookupOrderRequest
     * @return
     *     returns com.docking.wsdl.xlt.LookupOrderInfoLoadResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public LookupOrderInfoLoadResponse lookupOrderInfoLoad(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "lookupOrderRequest", partName = "lookupOrderRequest")
        LookupOrderRequest lookupOrderRequest);

    /**
     * 
     * @param userToken
     * @param createOrderRequest
     * @return
     *     returns com.docking.wsdl.xlt.CreateOrderResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public CreateOrderResponse createAndAuditOrder(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken,
        @WebParam(name = "createOrderRequest", partName = "createOrderRequest")
        CreateOrderRequest createOrderRequest);

    /**
     * 
     * @param userToken
     * @return
     *     returns com.docking.wsdl.xlt.GetTransportWayListResponse
     */
    @WebMethod
    @WebResult(partName = "return")
    public GetTransportWayListResponse getTransportWayList(
        @WebParam(name = "userToken", partName = "userToken")
        String userToken);

}
